// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2.2 (64-bit)
// Version: 2022.2.2
// Copyright (C) Copyright 1986-2023 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module setup_joint_aie_setup_joint_aie_Pipeline_VITIS_LOOP_68_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        s_0_TREADY,
        s_1_TREADY,
        s_2_TREADY,
        s_3_TREADY,
        s_4_TREADY,
        s_5_TREADY,
        s_6_TREADY,
        s_7_TREADY,
        histogram_rows,
        s_0_TDATA,
        s_0_TVALID,
        s_1_TDATA,
        s_1_TVALID,
        s_2_TDATA,
        s_2_TVALID,
        s_3_TDATA,
        s_3_TVALID,
        s_4_TDATA,
        s_4_TVALID,
        s_5_TDATA,
        s_5_TVALID,
        s_6_TDATA,
        s_6_TVALID,
        s_7_TDATA,
        s_7_TVALID,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [255:0] m_axi_gmem0_WDATA;
output  [31:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [255:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input   s_0_TREADY;
input   s_1_TREADY;
input   s_2_TREADY;
input   s_3_TREADY;
input   s_4_TREADY;
input   s_5_TREADY;
input   s_6_TREADY;
input   s_7_TREADY;
input  [63:0] histogram_rows;
output  [31:0] s_0_TDATA;
output   s_0_TVALID;
output  [31:0] s_1_TDATA;
output   s_1_TVALID;
output  [31:0] s_2_TDATA;
output   s_2_TVALID;
output  [31:0] s_3_TDATA;
output   s_3_TVALID;
output  [31:0] s_4_TDATA;
output   s_4_TVALID;
output  [31:0] s_5_TDATA;
output   s_5_TVALID;
output  [31:0] s_6_TDATA;
output   s_6_TVALID;
output  [31:0] s_7_TDATA;
output   s_7_TVALID;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

reg ap_idle;
reg m_axi_gmem0_ARVALID;
reg[63:0] m_axi_gmem0_ARADDR;
reg m_axi_gmem0_RREADY;
reg[31:0] s_0_TDATA;
reg s_0_TVALID;
reg[31:0] s_1_TDATA;
reg s_1_TVALID;
reg[31:0] s_2_TDATA;
reg s_2_TVALID;
reg[31:0] s_3_TDATA;
reg s_3_TVALID;
reg[31:0] s_4_TDATA;
reg s_4_TVALID;
reg[31:0] s_5_TDATA;
reg s_5_TVALID;
reg[31:0] s_6_TDATA;
reg s_6_TVALID;
reg[31:0] s_7_TDATA;
reg s_7_TVALID;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
reg   [0:0] icmp_ln68_reg_1212;
reg    ap_block_state8_io;
wire    ap_block_state16_pp0_stage7_iter1;
wire    ap_block_state24_pp0_stage7_iter2;
wire    ap_block_state32_pp0_stage7_iter3;
wire    ap_block_state40_pp0_stage7_iter4;
wire    ap_block_state48_pp0_stage7_iter5;
wire    ap_block_state56_pp0_stage7_iter6;
wire    ap_block_state64_pp0_stage7_iter7;
reg    ap_block_state72_pp0_stage7_iter8;
reg    ap_block_state80_pp0_stage7_iter9;
reg    ap_block_state80_io;
reg    ap_block_pp0_stage7_subdone;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage7;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
reg    s_0_TDATA_blk_n;
reg    s_1_TDATA_blk_n;
reg    s_2_TDATA_blk_n;
reg    s_3_TDATA_blk_n;
reg    s_4_TDATA_blk_n;
reg    s_5_TDATA_blk_n;
reg    s_6_TDATA_blk_n;
reg    s_7_TDATA_blk_n;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state9_pp0_stage0_iter1;
wire    ap_block_state17_pp0_stage0_iter2;
wire    ap_block_state25_pp0_stage0_iter3;
wire    ap_block_state33_pp0_stage0_iter4;
wire    ap_block_state41_pp0_stage0_iter5;
wire    ap_block_state49_pp0_stage0_iter6;
wire    ap_block_state57_pp0_stage0_iter7;
wire    ap_block_state65_pp0_stage0_iter8;
reg    ap_block_state73_pp0_stage0_iter9;
reg    ap_block_state81_pp0_stage0_iter10;
reg    ap_block_state81_io;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln68_fu_300_p2;
reg   [0:0] icmp_ln68_reg_1212_pp0_iter1_reg;
reg   [0:0] icmp_ln68_reg_1212_pp0_iter2_reg;
reg   [0:0] icmp_ln68_reg_1212_pp0_iter3_reg;
reg   [0:0] icmp_ln68_reg_1212_pp0_iter4_reg;
reg   [0:0] icmp_ln68_reg_1212_pp0_iter5_reg;
reg   [0:0] icmp_ln68_reg_1212_pp0_iter6_reg;
reg   [0:0] icmp_ln68_reg_1212_pp0_iter7_reg;
reg   [0:0] icmp_ln68_reg_1212_pp0_iter8_reg;
reg   [0:0] icmp_ln68_reg_1212_pp0_iter9_reg;
wire   [9:0] trunc_ln70_fu_306_p1;
reg   [9:0] trunc_ln70_reg_1216;
reg   [58:0] trunc_ln70_8_reg_1224;
wire  signed [15:0] zext_ln70_7_cast_fu_343_p4;
reg  signed [15:0] zext_ln70_7_cast_reg_1229;
wire    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state2_io;
wire    ap_block_state10_pp0_stage1_iter1;
wire    ap_block_state18_pp0_stage1_iter2;
wire    ap_block_state26_pp0_stage1_iter3;
wire    ap_block_state34_pp0_stage1_iter4;
wire    ap_block_state42_pp0_stage1_iter5;
wire    ap_block_state50_pp0_stage1_iter6;
wire    ap_block_state58_pp0_stage1_iter7;
wire    ap_block_state66_pp0_stage1_iter8;
reg    ap_block_state74_pp0_stage1_iter9;
reg    ap_block_state82_pp0_stage1_iter10;
reg    ap_block_state82_io;
reg    ap_block_pp0_stage1_11001;
reg   [58:0] trunc_ln79_8_reg_1241;
wire  signed [16:0] zext_ln70_6_cast_fu_381_p4;
reg  signed [16:0] zext_ln70_6_cast_reg_1246;
wire    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_state3_io;
wire    ap_block_state11_pp0_stage2_iter1;
wire    ap_block_state19_pp0_stage2_iter2;
wire    ap_block_state27_pp0_stage2_iter3;
wire    ap_block_state35_pp0_stage2_iter4;
wire    ap_block_state43_pp0_stage2_iter5;
wire    ap_block_state51_pp0_stage2_iter6;
wire    ap_block_state59_pp0_stage2_iter7;
wire    ap_block_state67_pp0_stage2_iter8;
reg    ap_block_state75_pp0_stage2_iter9;
reg    ap_block_state83_pp0_stage2_iter10;
reg    ap_block_state83_io;
reg    ap_block_pp0_stage2_11001;
reg   [58:0] trunc_ln88_8_reg_1257;
wire    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_state4_io;
wire    ap_block_state12_pp0_stage3_iter1;
wire    ap_block_state20_pp0_stage3_iter2;
wire    ap_block_state28_pp0_stage3_iter3;
wire    ap_block_state36_pp0_stage3_iter4;
wire    ap_block_state44_pp0_stage3_iter5;
wire    ap_block_state52_pp0_stage3_iter6;
wire    ap_block_state60_pp0_stage3_iter7;
wire    ap_block_state68_pp0_stage3_iter8;
reg    ap_block_state76_pp0_stage3_iter9;
reg    ap_block_state84_pp0_stage3_iter10;
reg    ap_block_state84_io;
reg    ap_block_pp0_stage3_11001;
reg   [58:0] trunc_ln97_8_reg_1268;
wire    ap_block_state5_pp0_stage4_iter0;
reg    ap_block_state5_io;
wire    ap_block_state13_pp0_stage4_iter1;
wire    ap_block_state21_pp0_stage4_iter2;
wire    ap_block_state29_pp0_stage4_iter3;
wire    ap_block_state37_pp0_stage4_iter4;
wire    ap_block_state45_pp0_stage4_iter5;
wire    ap_block_state53_pp0_stage4_iter6;
wire    ap_block_state61_pp0_stage4_iter7;
wire    ap_block_state69_pp0_stage4_iter8;
reg    ap_block_state77_pp0_stage4_iter9;
reg    ap_block_state85_pp0_stage4_iter10;
reg    ap_block_state85_io;
reg    ap_block_pp0_stage4_11001;
reg   [58:0] trunc_ln106_8_reg_1279;
wire    ap_block_state6_pp0_stage5_iter0;
reg    ap_block_state6_io;
wire    ap_block_state14_pp0_stage5_iter1;
wire    ap_block_state22_pp0_stage5_iter2;
wire    ap_block_state30_pp0_stage5_iter3;
wire    ap_block_state38_pp0_stage5_iter4;
wire    ap_block_state46_pp0_stage5_iter5;
wire    ap_block_state54_pp0_stage5_iter6;
wire    ap_block_state62_pp0_stage5_iter7;
wire    ap_block_state70_pp0_stage5_iter8;
reg    ap_block_state78_pp0_stage5_iter9;
reg    ap_block_state86_pp0_stage5_iter10;
reg    ap_block_state86_io;
reg    ap_block_pp0_stage5_11001;
reg   [58:0] trunc_ln115_8_reg_1290;
wire    ap_block_state7_pp0_stage6_iter0;
reg    ap_block_state7_io;
wire    ap_block_state15_pp0_stage6_iter1;
wire    ap_block_state23_pp0_stage6_iter2;
wire    ap_block_state31_pp0_stage6_iter3;
wire    ap_block_state39_pp0_stage6_iter4;
wire    ap_block_state47_pp0_stage6_iter5;
wire    ap_block_state55_pp0_stage6_iter6;
wire    ap_block_state63_pp0_stage6_iter7;
wire    ap_block_state71_pp0_stage6_iter8;
reg    ap_block_state79_pp0_stage6_iter9;
reg    ap_block_state79_io;
reg    ap_block_pp0_stage6_11001;
reg   [58:0] trunc_ln124_8_reg_1301;
reg    ap_block_pp0_stage7_11001;
reg   [58:0] trunc_ln133_8_reg_1312;
wire   [31:0] trunc_ln70_1_fu_601_p1;
reg   [31:0] trunc_ln70_1_reg_1323;
reg   [31:0] p_s_reg_1328;
reg   [31:0] p_1_reg_1333;
reg   [31:0] p_1_reg_1333_pp0_iter9_reg;
reg   [31:0] p_2_reg_1338;
reg   [31:0] p_2_reg_1338_pp0_iter9_reg;
reg   [31:0] p_3_reg_1343;
reg   [31:0] p_3_reg_1343_pp0_iter9_reg;
reg   [31:0] p_4_reg_1348;
reg   [31:0] p_4_reg_1348_pp0_iter9_reg;
reg   [31:0] p_5_reg_1353;
reg   [31:0] p_5_reg_1353_pp0_iter9_reg;
reg   [31:0] p_6_reg_1358;
reg   [31:0] p_6_reg_1358_pp0_iter9_reg;
wire   [31:0] trunc_ln79_fu_675_p1;
reg   [31:0] trunc_ln79_reg_1363;
reg   [31:0] p_7_reg_1368;
reg   [31:0] p_8_reg_1373;
reg   [31:0] p_9_reg_1378;
reg   [31:0] p_9_reg_1378_pp0_iter10_reg;
reg   [31:0] p_10_reg_1383;
reg   [31:0] p_10_reg_1383_pp0_iter10_reg;
reg   [31:0] p_11_reg_1388;
reg   [31:0] p_11_reg_1388_pp0_iter10_reg;
reg   [31:0] p_12_reg_1393;
reg   [31:0] p_12_reg_1393_pp0_iter10_reg;
reg   [31:0] p_13_reg_1398;
reg   [31:0] p_13_reg_1398_pp0_iter10_reg;
wire   [31:0] trunc_ln88_fu_749_p1;
reg   [31:0] trunc_ln88_reg_1403;
reg   [31:0] p_14_reg_1408;
reg   [31:0] p_15_reg_1413;
reg   [31:0] p_16_reg_1418;
reg   [31:0] p_17_reg_1423;
reg   [31:0] p_17_reg_1423_pp0_iter10_reg;
reg   [31:0] p_18_reg_1428;
reg   [31:0] p_18_reg_1428_pp0_iter10_reg;
reg   [31:0] p_19_reg_1433;
reg   [31:0] p_19_reg_1433_pp0_iter10_reg;
reg   [31:0] p_20_reg_1438;
reg   [31:0] p_20_reg_1438_pp0_iter10_reg;
wire   [31:0] trunc_ln97_fu_823_p1;
reg   [31:0] trunc_ln97_reg_1443;
reg   [31:0] p_21_reg_1448;
reg   [31:0] p_22_reg_1453;
reg   [31:0] p_23_reg_1458;
reg   [31:0] p_24_reg_1463;
reg   [31:0] p_25_reg_1468;
reg   [31:0] p_25_reg_1468_pp0_iter10_reg;
reg   [31:0] p_26_reg_1473;
reg   [31:0] p_26_reg_1473_pp0_iter10_reg;
reg   [31:0] p_27_reg_1478;
reg   [31:0] p_27_reg_1478_pp0_iter10_reg;
wire   [31:0] trunc_ln106_fu_897_p1;
reg   [31:0] trunc_ln106_reg_1483;
reg   [31:0] p_28_reg_1488;
reg   [31:0] p_29_reg_1493;
reg   [31:0] p_30_reg_1498;
reg   [31:0] p_31_reg_1503;
reg   [31:0] p_32_reg_1508;
reg   [31:0] p_33_reg_1513;
reg   [31:0] p_33_reg_1513_pp0_iter10_reg;
reg   [31:0] p_34_reg_1518;
reg   [31:0] p_34_reg_1518_pp0_iter10_reg;
wire   [31:0] trunc_ln115_fu_971_p1;
reg   [31:0] trunc_ln115_reg_1523;
reg   [31:0] p_35_reg_1528;
reg   [31:0] p_36_reg_1533;
reg   [31:0] p_37_reg_1538;
reg   [31:0] p_38_reg_1543;
reg   [31:0] p_39_reg_1548;
reg   [31:0] p_40_reg_1553;
reg   [31:0] p_41_reg_1558;
reg   [31:0] p_41_reg_1558_pp0_iter10_reg;
wire   [31:0] trunc_ln124_fu_1045_p1;
reg   [31:0] trunc_ln124_reg_1563;
reg   [31:0] p_42_reg_1568;
reg   [31:0] p_43_reg_1573;
reg   [31:0] p_44_reg_1578;
reg   [31:0] p_45_reg_1583;
reg   [31:0] p_46_reg_1588;
reg   [31:0] p_47_reg_1593;
reg   [31:0] p_48_reg_1598;
reg   [31:0] p_49_reg_1603;
reg   [31:0] p_50_reg_1608;
reg   [31:0] p_51_reg_1613;
reg   [31:0] p_52_reg_1618;
reg   [31:0] p_53_reg_1623;
reg   [31:0] p_54_reg_1628;
reg   [31:0] p_0_reg_1633;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage5_subdone;
wire  signed [63:0] sext_ln70_fu_361_p1;
wire  signed [63:0] sext_ln79_fu_399_p1;
wire  signed [63:0] sext_ln88_fu_431_p1;
wire  signed [63:0] sext_ln97_fu_469_p1;
wire  signed [63:0] sext_ln106_fu_507_p1;
wire  signed [63:0] sext_ln115_fu_539_p1;
wire  signed [63:0] sext_ln124_fu_571_p1;
wire  signed [63:0] sext_ln133_fu_591_p1;
reg   [10:0] j_fu_124;
wire   [10:0] add_ln68_fu_294_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_j_1;
reg    ap_block_pp0_stage6_01001;
reg    ap_block_pp0_stage7_01001;
reg    ap_block_pp0_stage0_01001;
reg    ap_block_pp0_stage1_01001;
reg    ap_block_pp0_stage2_01001;
reg    ap_block_pp0_stage3_01001;
reg    ap_block_pp0_stage4_01001;
reg    ap_block_pp0_stage5_01001;
wire   [31:0] trunc_ln133_fu_1119_p1;
wire   [14:0] shl_ln_fu_310_p3;
wire   [63:0] zext_ln70_fu_318_p1;
wire   [63:0] add_ln70_7_fu_322_p2;
wire   [63:0] zext_ln70_7_fu_352_p1;
wire   [63:0] add_ln70_6_fu_356_p2;
wire   [63:0] zext_ln70_6_fu_390_p1;
wire   [63:0] add_ln70_5_fu_394_p2;
wire  signed [16:0] sext_ln70_3_fu_419_p1;
wire   [63:0] zext_ln70_5_fu_422_p1;
wire   [63:0] add_ln70_4_fu_426_p2;
wire   [17:0] zext_ln70_4_cast_fu_451_p4;
wire   [63:0] zext_ln70_4_fu_460_p1;
wire   [63:0] add_ln70_3_fu_464_p2;
wire   [17:0] zext_ln70_3_cast_fu_489_p4;
wire   [63:0] zext_ln70_3_fu_498_p1;
wire   [63:0] add_ln70_2_fu_502_p2;
wire  signed [17:0] sext_ln70_2_fu_527_p1;
wire   [63:0] zext_ln70_2_fu_530_p1;
wire   [63:0] add_ln70_1_fu_534_p2;
wire  signed [17:0] sext_ln70_1_fu_559_p1;
wire   [63:0] zext_ln70_1_fu_562_p1;
wire   [63:0] add_ln70_fu_566_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter9_stage5;
reg    ap_idle_pp0_0to8;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [7:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to10;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage6_subdone;
wire    ap_ext_blocking_cur_n;
wire    ap_str_blocking_cur_n;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

setup_joint_aie_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage7)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_subdone))) begin
            ap_enable_reg_pp0_iter10 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter9_stage5) & (ap_idle_pp0_0to8 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter9_stage5) & (ap_idle_pp0_0to8 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter9_stage5) & (ap_idle_pp0_0to8 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter9_stage5) & (ap_idle_pp0_0to8 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter9_stage5) & (ap_idle_pp0_0to8 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter9_stage5) & (ap_idle_pp0_0to8 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter9_stage5) & (ap_idle_pp0_0to8 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter9_stage5) & (ap_idle_pp0_0to8 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter9_stage5) & (ap_idle_pp0_0to8 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln68_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_124 <= add_ln68_fu_294_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_124 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln68_reg_1212 <= icmp_ln68_fu_300_p2;
        icmp_ln68_reg_1212_pp0_iter1_reg <= icmp_ln68_reg_1212;
        icmp_ln68_reg_1212_pp0_iter2_reg <= icmp_ln68_reg_1212_pp0_iter1_reg;
        icmp_ln68_reg_1212_pp0_iter3_reg <= icmp_ln68_reg_1212_pp0_iter2_reg;
        icmp_ln68_reg_1212_pp0_iter4_reg <= icmp_ln68_reg_1212_pp0_iter3_reg;
        icmp_ln68_reg_1212_pp0_iter5_reg <= icmp_ln68_reg_1212_pp0_iter4_reg;
        icmp_ln68_reg_1212_pp0_iter6_reg <= icmp_ln68_reg_1212_pp0_iter5_reg;
        icmp_ln68_reg_1212_pp0_iter7_reg <= icmp_ln68_reg_1212_pp0_iter6_reg;
        icmp_ln68_reg_1212_pp0_iter8_reg <= icmp_ln68_reg_1212_pp0_iter7_reg;
        icmp_ln68_reg_1212_pp0_iter9_reg <= icmp_ln68_reg_1212_pp0_iter8_reg;
        p_10_reg_1383 <= {{m_axi_gmem0_RDATA[159:128]}};
        p_10_reg_1383_pp0_iter10_reg <= p_10_reg_1383;
        p_11_reg_1388 <= {{m_axi_gmem0_RDATA[191:160]}};
        p_11_reg_1388_pp0_iter10_reg <= p_11_reg_1388;
        p_12_reg_1393 <= {{m_axi_gmem0_RDATA[223:192]}};
        p_12_reg_1393_pp0_iter10_reg <= p_12_reg_1393;
        p_13_reg_1398 <= {{m_axi_gmem0_RDATA[255:224]}};
        p_13_reg_1398_pp0_iter10_reg <= p_13_reg_1398;
        p_7_reg_1368 <= {{m_axi_gmem0_RDATA[63:32]}};
        p_8_reg_1373 <= {{m_axi_gmem0_RDATA[95:64]}};
        p_9_reg_1378 <= {{m_axi_gmem0_RDATA[127:96]}};
        p_9_reg_1378_pp0_iter10_reg <= p_9_reg_1378;
        trunc_ln79_reg_1363 <= trunc_ln79_fu_675_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        p_0_reg_1633 <= {{m_axi_gmem0_RDATA[255:224]}};
        p_49_reg_1603 <= {{m_axi_gmem0_RDATA[63:32]}};
        p_50_reg_1608 <= {{m_axi_gmem0_RDATA[95:64]}};
        p_51_reg_1613 <= {{m_axi_gmem0_RDATA[127:96]}};
        p_52_reg_1618 <= {{m_axi_gmem0_RDATA[159:128]}};
        p_53_reg_1623 <= {{m_axi_gmem0_RDATA[191:160]}};
        p_54_reg_1628 <= {{m_axi_gmem0_RDATA[223:192]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        p_14_reg_1408 <= {{m_axi_gmem0_RDATA[63:32]}};
        p_15_reg_1413 <= {{m_axi_gmem0_RDATA[95:64]}};
        p_16_reg_1418 <= {{m_axi_gmem0_RDATA[127:96]}};
        p_17_reg_1423 <= {{m_axi_gmem0_RDATA[159:128]}};
        p_17_reg_1423_pp0_iter10_reg <= p_17_reg_1423;
        p_18_reg_1428 <= {{m_axi_gmem0_RDATA[191:160]}};
        p_18_reg_1428_pp0_iter10_reg <= p_18_reg_1428;
        p_19_reg_1433 <= {{m_axi_gmem0_RDATA[223:192]}};
        p_19_reg_1433_pp0_iter10_reg <= p_19_reg_1433;
        p_20_reg_1438 <= {{m_axi_gmem0_RDATA[255:224]}};
        p_20_reg_1438_pp0_iter10_reg <= p_20_reg_1438;
        trunc_ln88_reg_1403 <= trunc_ln88_fu_749_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        p_1_reg_1333 <= {{m_axi_gmem0_RDATA[95:64]}};
        p_1_reg_1333_pp0_iter9_reg <= p_1_reg_1333;
        p_2_reg_1338 <= {{m_axi_gmem0_RDATA[127:96]}};
        p_2_reg_1338_pp0_iter9_reg <= p_2_reg_1338;
        p_3_reg_1343 <= {{m_axi_gmem0_RDATA[159:128]}};
        p_3_reg_1343_pp0_iter9_reg <= p_3_reg_1343;
        p_4_reg_1348 <= {{m_axi_gmem0_RDATA[191:160]}};
        p_4_reg_1348_pp0_iter9_reg <= p_4_reg_1348;
        p_5_reg_1353 <= {{m_axi_gmem0_RDATA[223:192]}};
        p_5_reg_1353_pp0_iter9_reg <= p_5_reg_1353;
        p_6_reg_1358 <= {{m_axi_gmem0_RDATA[255:224]}};
        p_6_reg_1358_pp0_iter9_reg <= p_6_reg_1358;
        p_s_reg_1328 <= {{m_axi_gmem0_RDATA[63:32]}};
        trunc_ln70_1_reg_1323 <= trunc_ln70_1_fu_601_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        p_21_reg_1448 <= {{m_axi_gmem0_RDATA[63:32]}};
        p_22_reg_1453 <= {{m_axi_gmem0_RDATA[95:64]}};
        p_23_reg_1458 <= {{m_axi_gmem0_RDATA[127:96]}};
        p_24_reg_1463 <= {{m_axi_gmem0_RDATA[159:128]}};
        p_25_reg_1468 <= {{m_axi_gmem0_RDATA[191:160]}};
        p_25_reg_1468_pp0_iter10_reg <= p_25_reg_1468;
        p_26_reg_1473 <= {{m_axi_gmem0_RDATA[223:192]}};
        p_26_reg_1473_pp0_iter10_reg <= p_26_reg_1473;
        p_27_reg_1478 <= {{m_axi_gmem0_RDATA[255:224]}};
        p_27_reg_1478_pp0_iter10_reg <= p_27_reg_1478;
        trunc_ln97_reg_1443 <= trunc_ln97_fu_823_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        p_28_reg_1488 <= {{m_axi_gmem0_RDATA[63:32]}};
        p_29_reg_1493 <= {{m_axi_gmem0_RDATA[95:64]}};
        p_30_reg_1498 <= {{m_axi_gmem0_RDATA[127:96]}};
        p_31_reg_1503 <= {{m_axi_gmem0_RDATA[159:128]}};
        p_32_reg_1508 <= {{m_axi_gmem0_RDATA[191:160]}};
        p_33_reg_1513 <= {{m_axi_gmem0_RDATA[223:192]}};
        p_33_reg_1513_pp0_iter10_reg <= p_33_reg_1513;
        p_34_reg_1518 <= {{m_axi_gmem0_RDATA[255:224]}};
        p_34_reg_1518_pp0_iter10_reg <= p_34_reg_1518;
        trunc_ln106_reg_1483 <= trunc_ln106_fu_897_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        p_35_reg_1528 <= {{m_axi_gmem0_RDATA[63:32]}};
        p_36_reg_1533 <= {{m_axi_gmem0_RDATA[95:64]}};
        p_37_reg_1538 <= {{m_axi_gmem0_RDATA[127:96]}};
        p_38_reg_1543 <= {{m_axi_gmem0_RDATA[159:128]}};
        p_39_reg_1548 <= {{m_axi_gmem0_RDATA[191:160]}};
        p_40_reg_1553 <= {{m_axi_gmem0_RDATA[223:192]}};
        p_41_reg_1558 <= {{m_axi_gmem0_RDATA[255:224]}};
        p_41_reg_1558_pp0_iter10_reg <= p_41_reg_1558;
        trunc_ln115_reg_1523 <= trunc_ln115_fu_971_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        p_42_reg_1568 <= {{m_axi_gmem0_RDATA[63:32]}};
        p_43_reg_1573 <= {{m_axi_gmem0_RDATA[95:64]}};
        p_44_reg_1578 <= {{m_axi_gmem0_RDATA[127:96]}};
        p_45_reg_1583 <= {{m_axi_gmem0_RDATA[159:128]}};
        p_46_reg_1588 <= {{m_axi_gmem0_RDATA[191:160]}};
        p_47_reg_1593 <= {{m_axi_gmem0_RDATA[223:192]}};
        p_48_reg_1598 <= {{m_axi_gmem0_RDATA[255:224]}};
        trunc_ln124_reg_1563 <= trunc_ln124_fu_1045_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        trunc_ln106_8_reg_1279 <= {{add_ln70_3_fu_464_p2[63:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        trunc_ln115_8_reg_1290 <= {{add_ln70_2_fu_502_p2[63:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        trunc_ln124_8_reg_1301 <= {{add_ln70_1_fu_534_p2[63:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        trunc_ln133_8_reg_1312 <= {{add_ln70_fu_566_p2[63:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln68_fu_300_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln70_8_reg_1224 <= {{add_ln70_7_fu_322_p2[63:5]}};
        trunc_ln70_reg_1216 <= trunc_ln70_fu_306_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        trunc_ln79_8_reg_1241 <= {{add_ln70_6_fu_356_p2[63:5]}};
        zext_ln70_7_cast_reg_1229[14 : 5] <= zext_ln70_7_cast_fu_343_p4[14 : 5];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        trunc_ln88_8_reg_1257 <= {{add_ln70_5_fu_394_p2[63:5]}};
        zext_ln70_6_cast_reg_1246[14 : 5] <= zext_ln70_6_cast_fu_381_p4[14 : 5];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        trunc_ln97_8_reg_1268 <= {{add_ln70_4_fu_426_p2[63:5]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone) & (icmp_ln68_reg_1212 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln68_reg_1212_pp0_iter9_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_subdone))) begin
        ap_condition_exit_pp0_iter9_stage5 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter9_stage5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to8 = 1'b1;
    end else begin
        ap_idle_pp0_0to8 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to10 = 1'b1;
    end else begin
        ap_idle_pp0_1to10 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_124;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (icmp_ln68_reg_1212 == 1'd0)))) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem0_ARADDR = sext_ln133_fu_591_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        m_axi_gmem0_ARADDR = sext_ln124_fu_571_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        m_axi_gmem0_ARADDR = sext_ln115_fu_539_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        m_axi_gmem0_ARADDR = sext_ln106_fu_507_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        m_axi_gmem0_ARADDR = sext_ln97_fu_469_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        m_axi_gmem0_ARADDR = sext_ln88_fu_431_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        m_axi_gmem0_ARADDR = sext_ln79_fu_399_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln68_reg_1212 == 1'd0))) begin
        m_axi_gmem0_ARADDR = sext_ln70_fu_361_p1;
    end else begin
        m_axi_gmem0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln68_reg_1212 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln68_reg_1212 == 1'd0)))) begin
        m_axi_gmem0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_01001))) begin
        s_0_TDATA = p_6_reg_1358_pp0_iter9_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_01001))) begin
        s_0_TDATA = p_5_reg_1353_pp0_iter9_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001))) begin
        s_0_TDATA = p_4_reg_1348_pp0_iter9_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001))) begin
        s_0_TDATA = p_3_reg_1343_pp0_iter9_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        s_0_TDATA = p_2_reg_1338_pp0_iter9_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        s_0_TDATA = p_1_reg_1333_pp0_iter9_reg;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_01001))) begin
        s_0_TDATA = p_s_reg_1328;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_01001))) begin
        s_0_TDATA = trunc_ln70_1_reg_1323;
    end else begin
        s_0_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)))) begin
        s_0_TDATA_blk_n = s_0_TREADY;
    end else begin
        s_0_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)))) begin
        s_0_TVALID = 1'b1;
    end else begin
        s_0_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_01001))) begin
        s_1_TDATA = p_13_reg_1398_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_01001))) begin
        s_1_TDATA = p_12_reg_1393_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001))) begin
        s_1_TDATA = p_11_reg_1388_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001))) begin
        s_1_TDATA = p_10_reg_1383_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        s_1_TDATA = p_9_reg_1378_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        s_1_TDATA = p_8_reg_1373;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_01001))) begin
        s_1_TDATA = p_7_reg_1368;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_01001))) begin
        s_1_TDATA = trunc_ln79_reg_1363;
    end else begin
        s_1_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)))) begin
        s_1_TDATA_blk_n = s_1_TREADY;
    end else begin
        s_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)))) begin
        s_1_TVALID = 1'b1;
    end else begin
        s_1_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_01001))) begin
        s_2_TDATA = p_20_reg_1438_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_01001))) begin
        s_2_TDATA = p_19_reg_1433_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001))) begin
        s_2_TDATA = p_18_reg_1428_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001))) begin
        s_2_TDATA = p_17_reg_1423_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        s_2_TDATA = p_16_reg_1418;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        s_2_TDATA = p_15_reg_1413;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_01001))) begin
        s_2_TDATA = p_14_reg_1408;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_01001))) begin
        s_2_TDATA = trunc_ln88_reg_1403;
    end else begin
        s_2_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)))) begin
        s_2_TDATA_blk_n = s_2_TREADY;
    end else begin
        s_2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)))) begin
        s_2_TVALID = 1'b1;
    end else begin
        s_2_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_01001))) begin
        s_3_TDATA = p_27_reg_1478_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_01001))) begin
        s_3_TDATA = p_26_reg_1473_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001))) begin
        s_3_TDATA = p_25_reg_1468_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001))) begin
        s_3_TDATA = p_24_reg_1463;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        s_3_TDATA = p_23_reg_1458;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        s_3_TDATA = p_22_reg_1453;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_01001))) begin
        s_3_TDATA = p_21_reg_1448;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_01001))) begin
        s_3_TDATA = trunc_ln97_reg_1443;
    end else begin
        s_3_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)))) begin
        s_3_TDATA_blk_n = s_3_TREADY;
    end else begin
        s_3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)))) begin
        s_3_TVALID = 1'b1;
    end else begin
        s_3_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_01001))) begin
        s_4_TDATA = p_34_reg_1518_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_01001))) begin
        s_4_TDATA = p_33_reg_1513_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001))) begin
        s_4_TDATA = p_32_reg_1508;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001))) begin
        s_4_TDATA = p_31_reg_1503;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        s_4_TDATA = p_30_reg_1498;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        s_4_TDATA = p_29_reg_1493;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_01001))) begin
        s_4_TDATA = p_28_reg_1488;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_01001))) begin
        s_4_TDATA = trunc_ln106_reg_1483;
    end else begin
        s_4_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)))) begin
        s_4_TDATA_blk_n = s_4_TREADY;
    end else begin
        s_4_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)))) begin
        s_4_TVALID = 1'b1;
    end else begin
        s_4_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_01001))) begin
        s_5_TDATA = p_41_reg_1558_pp0_iter10_reg;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_01001))) begin
        s_5_TDATA = p_40_reg_1553;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001))) begin
        s_5_TDATA = p_39_reg_1548;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001))) begin
        s_5_TDATA = p_38_reg_1543;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        s_5_TDATA = p_37_reg_1538;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        s_5_TDATA = p_36_reg_1533;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_01001))) begin
        s_5_TDATA = p_35_reg_1528;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_01001))) begin
        s_5_TDATA = trunc_ln115_reg_1523;
    end else begin
        s_5_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)))) begin
        s_5_TDATA_blk_n = s_5_TREADY;
    end else begin
        s_5_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)))) begin
        s_5_TVALID = 1'b1;
    end else begin
        s_5_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_01001))) begin
        s_6_TDATA = p_48_reg_1598;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_01001))) begin
        s_6_TDATA = p_47_reg_1593;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001))) begin
        s_6_TDATA = p_46_reg_1588;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001))) begin
        s_6_TDATA = p_45_reg_1583;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        s_6_TDATA = p_44_reg_1578;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        s_6_TDATA = p_43_reg_1573;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_01001))) begin
        s_6_TDATA = p_42_reg_1568;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_01001))) begin
        s_6_TDATA = trunc_ln124_reg_1563;
    end else begin
        s_6_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)))) begin
        s_6_TDATA_blk_n = s_6_TREADY;
    end else begin
        s_6_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)))) begin
        s_6_TVALID = 1'b1;
    end else begin
        s_6_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_01001))) begin
        s_7_TDATA = p_0_reg_1633;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_01001))) begin
        s_7_TDATA = p_54_reg_1628;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_01001))) begin
        s_7_TDATA = p_53_reg_1623;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_01001))) begin
        s_7_TDATA = p_52_reg_1618;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001))) begin
        s_7_TDATA = p_51_reg_1613;
    end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        s_7_TDATA = p_50_reg_1608;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_01001))) begin
        s_7_TDATA = p_49_reg_1603;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_01001))) begin
        s_7_TDATA = trunc_ln133_fu_1119_p1;
    end else begin
        s_7_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)))) begin
        s_7_TDATA_blk_n = s_7_TREADY;
    end else begin
        s_7_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)))) begin
        s_7_TVALID = 1'b1;
    end else begin
        s_7_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to10 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter9_stage5) & (ap_idle_pp0_0to8 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln68_fu_294_p2 = (ap_sig_allocacmp_j_1 + 11'd1);

assign add_ln70_1_fu_534_p2 = (zext_ln70_2_fu_530_p1 + histogram_rows);

assign add_ln70_2_fu_502_p2 = (zext_ln70_3_fu_498_p1 + histogram_rows);

assign add_ln70_3_fu_464_p2 = (zext_ln70_4_fu_460_p1 + histogram_rows);

assign add_ln70_4_fu_426_p2 = (zext_ln70_5_fu_422_p1 + histogram_rows);

assign add_ln70_5_fu_394_p2 = (zext_ln70_6_fu_390_p1 + histogram_rows);

assign add_ln70_6_fu_356_p2 = (zext_ln70_7_fu_352_p1 + histogram_rows);

assign add_ln70_7_fu_322_p2 = (zext_ln70_fu_318_p1 + histogram_rows);

assign add_ln70_fu_566_p2 = (zext_ln70_1_fu_562_p1 + histogram_rows);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state81_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((m_axi_gmem0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state81_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((m_axi_gmem0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state82_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state82_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state83_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state83_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state84_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state84_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_01001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage4_11001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state85_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state85_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_01001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage5_11001 = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state86_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = (((ap_enable_reg_pp0_iter10 == 1'b1) & ((1'b1 == ap_block_state86_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_01001 = ((ap_enable_reg_pp0_iter9 == 1'b1) & ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0) | (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage6_11001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & ((1'b1 == ap_block_state79_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0) | (m_axi_gmem0_RVALID == 1'b0))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_io)));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = (((ap_enable_reg_pp0_iter9 == 1'b1) & ((1'b1 == ap_block_state79_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0) | (m_axi_gmem0_RVALID == 1'b0))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state7_io)));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_01001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage7_11001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & ((1'b1 == ap_block_state80_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_io)));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = (((ap_enable_reg_pp0_iter9 == 1'b1) & ((1'b1 == ap_block_state80_io) | (s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0))) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state8_io)));
end

assign ap_block_state10_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage7_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage6_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage7_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_io = ((m_axi_gmem0_ARREADY == 1'b0) & (icmp_ln68_reg_1212 == 1'd0));
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage5_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage6_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage7_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage4_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage5_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage6_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((m_axi_gmem0_ARREADY == 1'b0) & (icmp_ln68_reg_1212 == 1'd0));
end

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage7_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage4_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage5_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage6_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage7_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((m_axi_gmem0_ARREADY == 1'b0) & (icmp_ln68_reg_1212 == 1'd0));
end

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage3_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage4_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage5_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp0_stage6_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp0_stage7_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state59_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((m_axi_gmem0_ARREADY == 1'b0) & (icmp_ln68_reg_1212 == 1'd0));
end

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state60_pp0_stage3_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state61_pp0_stage4_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state62_pp0_stage5_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state63_pp0_stage6_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state64_pp0_stage7_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state65_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state66_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state67_pp0_stage2_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state68_pp0_stage3_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state69_pp0_stage4_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_io = ((m_axi_gmem0_ARREADY == 1'b0) & (icmp_ln68_reg_1212 == 1'd0));
end

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state70_pp0_stage5_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state71_pp0_stage6_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state72_pp0_stage7_iter8 = (m_axi_gmem0_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state73_pp0_stage0_iter9 = (m_axi_gmem0_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state74_pp0_stage1_iter9 = (m_axi_gmem0_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state75_pp0_stage2_iter9 = (m_axi_gmem0_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state76_pp0_stage3_iter9 = (m_axi_gmem0_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state77_pp0_stage4_iter9 = (m_axi_gmem0_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state78_pp0_stage5_iter9 = (m_axi_gmem0_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state79_io = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state79_pp0_stage6_iter9 = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0) | (m_axi_gmem0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state7_io = ((m_axi_gmem0_ARREADY == 1'b0) & (icmp_ln68_reg_1212 == 1'd0));
end

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state80_io = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state80_pp0_stage7_iter9 = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state81_io = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state81_pp0_stage0_iter10 = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state82_io = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state82_pp0_stage1_iter10 = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state83_io = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state83_pp0_stage2_iter10 = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state84_io = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state84_pp0_stage3_iter10 = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state85_io = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state85_pp0_stage4_iter10 = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state86_io = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state86_pp0_stage5_iter10 = ((s_7_TREADY == 1'b0) | (s_6_TREADY == 1'b0) | (s_5_TREADY == 1'b0) | (s_4_TREADY == 1'b0) | (s_3_TREADY == 1'b0) | (s_2_TREADY == 1'b0) | (s_1_TREADY == 1'b0) | (s_0_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state8_io = ((m_axi_gmem0_ARREADY == 1'b0) & (icmp_ln68_reg_1212 == 1'd0));
end

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ext_blocking_cur_n = (gmem0_blk_n_R & gmem0_blk_n_AR);

assign ap_ext_blocking_n = (ap_ext_blocking_cur_n & 1'b1);

assign ap_int_blocking_n = (1'b1 & 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign ap_str_blocking_cur_n = (s_7_TDATA_blk_n & s_6_TDATA_blk_n & s_5_TDATA_blk_n & s_4_TDATA_blk_n & s_3_TDATA_blk_n & s_2_TDATA_blk_n & s_1_TDATA_blk_n & s_0_TDATA_blk_n);

assign ap_str_blocking_n = (ap_str_blocking_cur_n & 1'b1);

assign icmp_ln68_fu_300_p2 = ((ap_sig_allocacmp_j_1 == 11'd1024) ? 1'b1 : 1'b0);

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd1;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 256'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 32'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign sext_ln106_fu_507_p1 = $signed(trunc_ln106_8_reg_1279);

assign sext_ln115_fu_539_p1 = $signed(trunc_ln115_8_reg_1290);

assign sext_ln124_fu_571_p1 = $signed(trunc_ln124_8_reg_1301);

assign sext_ln133_fu_591_p1 = $signed(trunc_ln133_8_reg_1312);

assign sext_ln70_1_fu_559_p1 = zext_ln70_7_cast_reg_1229;

assign sext_ln70_2_fu_527_p1 = zext_ln70_6_cast_reg_1246;

assign sext_ln70_3_fu_419_p1 = zext_ln70_7_cast_reg_1229;

assign sext_ln70_fu_361_p1 = $signed(trunc_ln70_8_reg_1224);

assign sext_ln79_fu_399_p1 = $signed(trunc_ln79_8_reg_1241);

assign sext_ln88_fu_431_p1 = $signed(trunc_ln88_8_reg_1257);

assign sext_ln97_fu_469_p1 = $signed(trunc_ln97_8_reg_1268);

assign shl_ln_fu_310_p3 = {{trunc_ln70_fu_306_p1}, {5'd0}};

assign trunc_ln106_fu_897_p1 = m_axi_gmem0_RDATA[31:0];

assign trunc_ln115_fu_971_p1 = m_axi_gmem0_RDATA[31:0];

assign trunc_ln124_fu_1045_p1 = m_axi_gmem0_RDATA[31:0];

assign trunc_ln133_fu_1119_p1 = m_axi_gmem0_RDATA[31:0];

assign trunc_ln70_1_fu_601_p1 = m_axi_gmem0_RDATA[31:0];

assign trunc_ln70_fu_306_p1 = ap_sig_allocacmp_j_1[9:0];

assign trunc_ln79_fu_675_p1 = m_axi_gmem0_RDATA[31:0];

assign trunc_ln88_fu_749_p1 = m_axi_gmem0_RDATA[31:0];

assign trunc_ln97_fu_823_p1 = m_axi_gmem0_RDATA[31:0];

assign zext_ln70_1_fu_562_p1 = $unsigned(sext_ln70_1_fu_559_p1);

assign zext_ln70_2_fu_530_p1 = $unsigned(sext_ln70_2_fu_527_p1);

assign zext_ln70_3_cast_fu_489_p4 = {{{{3'd5}, {trunc_ln70_reg_1216}}}, {5'd0}};

assign zext_ln70_3_fu_498_p1 = zext_ln70_3_cast_fu_489_p4;

assign zext_ln70_4_cast_fu_451_p4 = {{{{3'd4}, {trunc_ln70_reg_1216}}}, {5'd0}};

assign zext_ln70_4_fu_460_p1 = zext_ln70_4_cast_fu_451_p4;

assign zext_ln70_5_fu_422_p1 = $unsigned(sext_ln70_3_fu_419_p1);

assign zext_ln70_6_cast_fu_381_p4 = {{{{2'd2}, {trunc_ln70_reg_1216}}}, {5'd0}};

assign zext_ln70_6_fu_390_p1 = $unsigned(zext_ln70_6_cast_fu_381_p4);

assign zext_ln70_7_cast_fu_343_p4 = {{{{1'd1}, {trunc_ln70_reg_1216}}}, {5'd0}};

assign zext_ln70_7_fu_352_p1 = $unsigned(zext_ln70_7_cast_fu_343_p4);

assign zext_ln70_fu_318_p1 = shl_ln_fu_310_p3;

always @ (posedge ap_clk) begin
    zext_ln70_7_cast_reg_1229[4:0] <= 5'b00000;
    zext_ln70_7_cast_reg_1229[15] <= 1'b1;
    zext_ln70_6_cast_reg_1246[4:0] <= 5'b00000;
    zext_ln70_6_cast_reg_1246[16:15] <= 2'b10;
end

endmodule //setup_joint_aie_setup_joint_aie_Pipeline_VITIS_LOOP_68_1
